### ISSUE TITLE
Question about the performance

### ISSUE THREAD

**Issue by nkliuyifang** [Jiaolong/self-supervised-da#1]
Dear Jiaolong,

First, thanks for your great work!

I have used your code with rotate_pacs_sketch.yaml.
The expected accuracy is 79.54%, while I only got 73.53%.

Could you help me with the problem?
Thanks a lot!

Best
Mengyuan

**Comment by Jiaolong** [comment]
Thanks for spoting this error, I have updated the results. After re-running the experiments, I got `74.49%`.
